name: Build report, send to telegram

on:
  push:
    branches: main

jobs:
  build_latex:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: src/
          latexmk_shell_escape: true
          extra_system_packages: "inkscape"
      - name: Send to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Guess who's back
          document: src/main.pdf
